# Generated by Django 3.0.7 on 2020-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200620_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_id', to='store.OrderItem'),
        ),
    ]
