# Generated by Django 3.0.7 on 2020-06-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='relatedOrder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
        ),
    ]
